#!/usr/bin/env python3
"""Per-app SNI allowlist proxy and DNS forwarder.

Bind host veth IPs from the proxy config; route TLS by namespace source IP.
TLS stays end to end. DNS answers are untrusted; SNI gates TLS connections.
"""

from __future__ import annotations

import argparse
import asyncio
import datetime
import json
import sys
from pathlib import Path

HELLO_TIMEOUT = 5.0
# LLM streams pause for a while; only reap truly dead connections.
SPLICE_IDLE_TIMEOUT = 900.0
DNS_TIMEOUT = 5.0
RELAY_CHUNK_SIZE = 64 * 1024

HTTPS_PORT = 443
DNS_PORT = 53
DNS_TCP_LENGTH_SIZE = 2
FALLBACK_DNS_SERVER = "1.1.1.1"

TLS_HANDSHAKE = 0x16
CLIENT_HELLO = 0x01
SNI_EXTENSION = 0x0000
HOST_NAME_TYPE = 0x00

TLS_UINT8_SIZE = 1
TLS_UINT16_SIZE = 2
TLS_RECORD_HEADER_SIZE = 5
TLS_RECORD_LENGTH_OFFSET = 3
TLS_HANDSHAKE_HEADER_SIZE = 4
TLS_RANDOM_SIZE = 32
CLIENT_HELLO_PREFIX_SIZE = TLS_HANDSHAKE_HEADER_SIZE + TLS_UINT16_SIZE + TLS_RANDOM_SIZE
TLS_EXTENSION_HEADER_SIZE = 2 * TLS_UINT16_SIZE
SNI_NAME_HEADER_SIZE = TLS_UINT8_SIZE + TLS_UINT16_SIZE

# Session ID, cipher suites, and compression methods have different length widths.
CLIENT_HELLO_LENGTH_FIELD_WIDTHS = (TLS_UINT8_SIZE, TLS_UINT16_SIZE, TLS_UINT8_SIZE)


async def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--apps-json", required=True, type=Path,
                        help="proxy config generated by host/up")
    parser.add_argument("--upstream-port", type=int, default=HTTPS_PORT,
                        help="upstream TLS port; override only for testing")
    parser.add_argument("--upstream-host", default=None,
                        help="fixed upstream host; default is the SNI name (testing only)")
    args = parser.parse_args()

    apps, sni_port, dns_port = load_proxy_config(args.apps_json)
    routes = {netns_ip: endpoints for _, netns_ip, endpoints in apps}
    sni_proxy = SniProxy(routes, args.upstream_port, args.upstream_host)
    dns_resolvers = upstream_resolvers()

    # Keep UDP transports referenced for the lifetime of the listeners.
    sni_servers = [
        await asyncio.start_server(sni_proxy.handle, ip, sni_port)
        for ip, _, _ in apps
    ]
    dns_tcp_servers = [
        await asyncio.start_server(handle_dns_tcp, ip, dns_port)
        for ip, _, _ in apps
    ]
    dns_udp_transports = [
        await start_dns_udp(ip, dns_port, dns_resolvers)
        for ip, _, _ in apps
    ]

    apps_summary = ", ".join(
        f"{ip}:{endpoints.app}({len(endpoints.entries)})"
        for ip, _, endpoints in apps
    )
    startup_detail = (
        f"snip={sni_port} dnsp={dns_port} "
        f"apps={{{apps_summary}}} upstream_dns={dns_resolvers}"
    )
    log("START", startup_detail)

    async with asyncio.TaskGroup() as group:
        for server in sni_servers + dns_tcp_servers:
            group.create_task(server.serve_forever())


class SniProxy:
    def __init__(self, apps: dict[str, Endpoints], upstream_port: int = HTTPS_PORT,
                 upstream_host: str | None = None):
        self.apps = apps
        self.upstream_port = upstream_port
        self.upstream_host = upstream_host  # fixed upstream; testing only

    async def handle(self, reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        peer = writer.get_extra_info("peername")
        peer_ip = peer[0] if peer else "?"
        app = self.apps.get(peer_ip)
        label = app.app if app else "unknown-source"
        try:
            client_hello = await self._read_client_hello(reader)
            if client_hello is None:
                log("DENY", f"{label} {peer_ip} not-tls")
                return
            handshake = client_hello[TLS_RECORD_HEADER_SIZE:]
            sni = sni_from_client_hello(handshake)

            if app is None or sni not in app:
                log("DENY", f"{label} {peer_ip} sni={sni or 'absent'}")
                return

            try:
                destination = self.upstream_host or sni
                connection = asyncio.open_connection(destination, self.upstream_port)
                upstream_reader, upstream_writer = await asyncio.wait_for(
                    connection, HELLO_TIMEOUT,
                )
            except OSError as exc:
                log("ERROR", f"{label} sni={sni} upstream connect failed: {exc}")
                return

            log("ALLOW", f"{label} {peer_ip} sni={sni}")
            try:
                upstream_writer.write(client_hello)
                await upstream_writer.drain()
                await splice(reader, writer, upstream_reader, upstream_writer)
            finally:
                upstream_writer.close()
        except (asyncio.IncompleteReadError, asyncio.TimeoutError):
            log("DENY", f"{label} {peer_ip} no-clienthello")
        except OSError as exc:
            log("ERROR", f"{label} {peer_ip} {exc}")
        finally:
            writer.close()

    @staticmethod
    async def _read_client_hello(reader: asyncio.StreamReader) -> bytes | None:
        """Read one TLS record; None if the first bytes are not a handshake."""
        header = await asyncio.wait_for(reader.readexactly(TLS_RECORD_HEADER_SIZE), HELLO_TIMEOUT)
        if header[0] != TLS_HANDSHAKE:
            return None
        record_length = int.from_bytes(header[TLS_RECORD_LENGTH_OFFSET:TLS_RECORD_HEADER_SIZE], "big")
        body = await asyncio.wait_for(reader.readexactly(record_length), HELLO_TIMEOUT)
        return header + body


class Endpoints:
    def __init__(self, app: str, entries: list[str]):
        self.app = app
        self.entries = frozenset(
            normalized
            for raw in entries
            if (normalized := raw.strip().lower().rstrip("."))
        )
        if not self.entries:
            raise SystemExit(f"app '{app}' has no endpoints; refusing to run wide open")

    def __contains__(self, sni: str | None) -> bool:
        return sni is not None and sni in self.entries


def load_proxy_config(config: Path) -> tuple[list[tuple[str, str, Endpoints]], int, int]:
    """Load listener IPs, namespace source IPs, endpoint lists, and ports."""
    try:
        data = json.loads(config.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise SystemExit(f"cannot read proxy config {config}: {exc}")
    apps = [
        (entry["ip"], entry["netns_ip"], Endpoints(entry["name"], entry["endpoints"]))
        for entry in data["apps"]
    ]
    if not apps:
        raise SystemExit(f"{config} declares no apps; refusing to run")

    sni_port = int(data["proxy"]["sni_port"])
    dns_port = int(data["proxy"]["dns_port"])
    return apps, sni_port, dns_port


def sni_from_client_hello(hello: bytes) -> str | None:
    """Extract the server_name from a complete ClientHello, or None."""
    if len(hello) < CLIENT_HELLO_PREFIX_SIZE or hello[0] != CLIENT_HELLO:
        return None
    handshake_length = int.from_bytes(hello[TLS_UINT8_SIZE:TLS_HANDSHAKE_HEADER_SIZE], "big")
    handshake_end = TLS_HANDSHAKE_HEADER_SIZE + handshake_length
    if handshake_end > len(hello):
        return None

    offset = CLIENT_HELLO_PREFIX_SIZE
    for width in CLIENT_HELLO_LENGTH_FIELD_WIDTHS:
        if offset + width > handshake_end:
            return None
        field_length = int.from_bytes(hello[offset:offset + width], "big")
        offset += width + field_length
        if offset > handshake_end:
            return None

    extensions_start = offset + TLS_UINT16_SIZE
    if extensions_start > handshake_end:
        return None
    extensions_length = int.from_bytes(hello[offset:extensions_start], "big")
    if extensions_start + extensions_length != handshake_end:
        return None
    return sni_from_extensions(hello[extensions_start:handshake_end])


def sni_from_extensions(extensions: bytes) -> str | None:
    offset = 0
    hostname = None
    while offset < len(extensions):
        extension_start = offset + TLS_EXTENSION_HEADER_SIZE
        if extension_start > len(extensions):
            return None
        length_offset = offset + TLS_UINT16_SIZE
        extension_type = int.from_bytes(extensions[offset:length_offset], "big")
        extension_length = int.from_bytes(extensions[length_offset:extension_start], "big")
        extension_end = extension_start + extension_length
        if extension_end > len(extensions):
            return None

        if extension_type == SNI_EXTENSION:
            if hostname is not None:
                return None
            hostname = sni_from_server_name_list(extensions[extension_start:extension_end])
            if hostname is None:
                return None

        offset = extension_end
    return hostname


def sni_from_server_name_list(body: bytes) -> str | None:
    """server_name_list: 2-byte length, then (type, 2-byte len, name)."""
    if len(body) < TLS_UINT16_SIZE:
        return None
    list_length = int.from_bytes(body[:TLS_UINT16_SIZE], "big")
    if list_length != len(body) - TLS_UINT16_SIZE:
        return None

    offset = TLS_UINT16_SIZE
    hostname = None
    while offset < len(body):
        name_start = offset + SNI_NAME_HEADER_SIZE
        if name_start > len(body):
            return None
        name_type = body[offset]
        length_offset = offset + TLS_UINT8_SIZE
        name_length = int.from_bytes(body[length_offset:name_start], "big")
        name_end = name_start + name_length
        if name_length == 0 or name_end > len(body):
            return None

        if name_type == HOST_NAME_TYPE:
            if hostname is not None:
                return None
            try:
                hostname = body[name_start:name_end].decode("ascii").lower()
            except UnicodeDecodeError:
                return None

        offset = name_end
    return hostname


async def splice(
    client_reader: asyncio.StreamReader, client_writer: asyncio.StreamWriter,
    upstream_reader: asyncio.StreamReader, upstream_writer: asyncio.StreamWriter,
) -> None:
    """Relay both directions until either side ends, then close both."""
    client_to_upstream = _pump(client_reader, upstream_writer)
    upstream_to_client = _pump(upstream_reader, client_writer)
    await asyncio.gather(client_to_upstream, upstream_to_client)
    client_writer.close()
    upstream_writer.close()


async def _pump(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
    try:
        while chunk := await asyncio.wait_for(reader.read(RELAY_CHUNK_SIZE), SPLICE_IDLE_TIMEOUT):
            writer.write(chunk)
            await writer.drain()
    except (asyncio.TimeoutError, OSError):
        pass
    finally:
        writer.close()


class DnsForwarder(asyncio.DatagramProtocol):
    def __init__(self, servers: list[str]):
        self.servers = servers
        self.transport: asyncio.DatagramTransport | None = None

    def connection_made(self, transport: asyncio.DatagramTransport) -> None:
        self.transport = transport

    def datagram_received(self, data: bytes, addr) -> None:
        loop = asyncio.get_running_loop()
        endpoint = loop.create_datagram_endpoint(
            lambda: DnsUplink(data, self.transport, addr),
            remote_addr=(self.servers[0], DNS_PORT),
        )
        uplink = loop.create_task(endpoint)
        uplink.add_done_callback(self._discard_failed_uplink)

    @staticmethod
    def _discard_failed_uplink(task: asyncio.Task) -> None:
        try:
            task.result()
        except OSError:
            pass  # No transport was created for an unreachable upstream.


class DnsUplink(asyncio.DatagramProtocol):
    """Forwards one query upstream and relays the first response back."""

    def __init__(self, query: bytes, reply: asyncio.DatagramTransport, client_addr):
        self.query = query
        self.reply = reply
        self.client_addr = client_addr
        self.transport: asyncio.DatagramTransport | None = None

    def connection_made(self, transport: asyncio.DatagramTransport) -> None:
        self.transport = transport
        transport.sendto(self.query)
        asyncio.get_running_loop().call_later(DNS_TIMEOUT, transport.close)

    def datagram_received(self, data: bytes, _addr) -> None:
        self.reply.sendto(data, self.client_addr)
        self.transport.close()

    def error_received(self, _exc: Exception) -> None:
        self.transport.close()


async def handle_dns_tcp(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
    """TCP DNS (clients fall back to this on truncation)."""
    server = upstream_resolvers()[0]
    try:
        while length_bytes := await asyncio.wait_for(reader.readexactly(DNS_TCP_LENGTH_SIZE), DNS_TIMEOUT):
            await relay_dns_tcp_query(length_bytes, reader, writer, server)
    except (asyncio.IncompleteReadError, asyncio.TimeoutError, OSError):
        pass
    finally:
        writer.close()


async def relay_dns_tcp_query(
    length_bytes: bytes, client_reader: asyncio.StreamReader,
    client_writer: asyncio.StreamWriter, server: str,
) -> None:
    """One query: fresh upstream connection, one response relayed back."""
    async with asyncio.timeout(DNS_TIMEOUT):
        query_length = int.from_bytes(length_bytes, "big")
        query = await client_reader.readexactly(query_length)
        upstream_reader, upstream_writer = await asyncio.open_connection(server, DNS_PORT)
        try:
            upstream_writer.write(length_bytes + query)
            await upstream_writer.drain()
            response_length_bytes = await upstream_reader.readexactly(DNS_TCP_LENGTH_SIZE)
            response_length = int.from_bytes(response_length_bytes, "big")
            response = await upstream_reader.readexactly(response_length)
            client_writer.write(response_length_bytes + response)
            await client_writer.drain()
        finally:
            upstream_writer.close()


async def start_dns_udp(ip: str, port: int, servers: list[str]) -> asyncio.DatagramTransport:
    loop = asyncio.get_running_loop()
    transport, _protocol = await loop.create_datagram_endpoint(
        lambda: DnsForwarder(servers), local_addr=(ip, port),
    )
    return transport


def upstream_resolvers() -> list[str]:
    servers = []
    for line in Path("/etc/resolv.conf").read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0] == "nameserver":
            servers.append(parts[1])
    return servers or [FALLBACK_DNS_SERVER]


def log(event: str, detail: str) -> None:
    timestamp = datetime.datetime.now(datetime.UTC).isoformat(timespec="seconds")
    print(f"{timestamp} {event} {detail}", file=sys.stderr, flush=True)


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
